export const GAMELIST = [
  {
    id: 0,
    name: "Castlevania Symphony Of The Night",
    image: "images/castlevaniaSOTNCover.jpg",
    genre: "Genre: Action-Adventure",
    console: "Console: PSX",
    type: "PSX",
    year: "Year: 1997",
  },
  {
    id: 1,
    name: "Gran Turismo ",
    image: "images/granTurismoCover.jpg",
    genre: "Genre: Driving/Racing, Simulation",
    console: "Console: PSX",
    type: "PSX",
    year: "Year: 1999",
  },
  {
    id: 3,
    name: "Resident Evil 3: Nemesis ",
    image: "images/residentEvil3Cover.jpg",
    genre: "Genre: Survivor Horror",
    console: "Console: PSX",
    type: "PSX",
    year: "Year: 1999",
  },
  {
    id: 4,
    name: "Parasite Eve",
    image: "images/parasiteEveCover.jpg",
    genre: "Genre: Action, Adventure, Role-Playing",
    console: "Console: PSX",
    type: "PSX",
    year: "Year: 1998",
  },
  {
    id: 5,
    name: "	Sonic the Hedgehogt",
    image: "images/sonicCover.png",
    genre: "Genre: Platform",
    console: "Console: Mega Drive",
    type: "Megadrive",
    year: "Year: 1991",
  },
  {
    id: 6,
    name: "Streets of Rage",
    image: "images/streetsofrageCover.png",
    genre: "Genre: Side-Scrolling Beat 'em Up",
    console: "Console: Mega Drive",
    type: "Megadrive",
    year: "Year: 1991",
  },
  {
    id: 7,
    name: "Castlevania - Bloodlines",
    image: "images/castlevaniaBloodlinesCover.jpg",
    genre: "Genre: Platform",
    console: "Console: Mega Drive",
    type: "Megadrive",
    year: "Year: 1994",
  },
  {
    id: 8,
    name: "Golden Axe II ",
    image: "images/goldenAxeIICover.jpg",
    genre: "Genre: Side-Scrolling Beat 'em Up",
    console: "Console: Mega Drive",
    type: "Megadrive",
    year: "Year: 1991",
  },
  {
    id: 9,
    name: "Sunset Riders",
    image: "images/sunsetridersCover.jpg",
    genre: "Genre: Side-Scrolling Run and Gun",
    console: "Console: Mega Drive",
    type: "Megadrive",
    year: "Year: 1991",
  },
  {
    id: 10,
    name: "Mickey and Donald - Magical Adventure 3",
    image: "images/mickeyDonaldCover.jpg",
    genre: "Genre: Action-Adventure",
    console: "Console: SNES",
    type: "SNES",
    year: "Year: 1995",
  },
  {
    id: 11,
    name: "Final Fantasy VI ",
    image: "images/finalFantasyVICover.jpg",
    genre: "Genre: Role-Playing",
    console: "Console: SNES",
    type: "SNES",
    year: "Year:  1994",
  },
  {
    id: 12,
    name: "Super Ghols 'n Ghost",
    image: "images/superGhoulsNGhostsCover.jpg",
    genre: "Genre:  Action Side-Scrolling Platform",
    console: "Console: SNES",
    type: "SNES",
    year: "Year: 1991",
  },
  {
    id: 13,
    name: "Super Metroid",
    image: "images/superMetroidCover.jpg",
    genre: "Genre: Action, Adventure",
    console: "Console: SNES",
    type: "SNES",
    year: "Year: 1994",
  },
  {
    id: 14,
    name: "Wild Guns",
    image: "images/WIldGunsCover.jpg",
    genre: "Genre:  Space Western Shooting Gallery",
    console: "Console: SNES",
    type: "SNES",
    year: "Year: 1996 ",
  },
];
