export const MEGADRIVE = [
  {
    id: 5,
    name: "Sonic the Hedgehogt",
    image: "images/sonicCover.png",
    genre: "Genre: Platform",
    console: "Console: Mega Drive",
    type: "Megadrive",
    year: "Year: 1991",
  },
  {
    id: 6,
    name: "Streets of Rage",
    image: "images/streetsofrageCover.png",
    genre: "Genre: Side-Scrolling Beat 'em Up",
    console: "Console: Mega Drive",
    type: "Megadrive",
    year: "Year: 1991",
  },
  {
    id: 7,
    name: "Castlevania - Bloodlines",
    image: "images/castlevaniaBloodlinesCover.jpg",
    genre: "Genre: Platform",
    console: "Console: Mega Drive",
    type: "Megadrive",
    year: "Year: 1994",
  },
  {
    id: 8,
    name: "Golden Axe II ",
    image: "images/goldenAxeIICover.jpg",
    genre: "Genre: Side-Scrolling Beat 'em Up",
    console: "Console: Mega Drive",
    type: "Megadrive",
    year: "Year: 1991",
  },
  {
    id: 9,
    name: "Sunset Riders",
    image: "images/sunsetridersCover.jpg",
    genre: "Genre: Side-Scrolling Run and Gun",
    console: "Console: Mega Drive",
    type: "Megadrive",
    year: "Year: 1991",
  },
];
