export const PSX = [
  {
    id: 0,
    name: "Castlevania Symphony Of The Night",
    image: "images/castlevaniaSOTNCover.jpg",
    genre: "Genre: Action-Adventure",
    console: "Console: PSX",
    type: "PSX",
    year: "Year: 1997",
  },
  {
    id: 1,
    name: "Gran Turismo ",
    image: "images/granTurismoCover.jpg",
    genre: "Genre: Driving/Racing, Simulation",
    console: "Console: PSX",
    type: "PSX",
    year: "Year: 1999",
  },
  {
    id: 3,
    name: "Resident Evil 3: Nemesis ",
    image: "images/residentEvil3Cover.jpg",
    genre: "Genre: Survivor Horror",
    console: "Console: PSX",
    type: "PSX",
    year: "Year: 1999",
  },
  {
    id: 4,
    name: "Parasite Eve",
    image: "images/parasiteEveCover.jpg",
    genre: "Genre: Action, Adventure, Role-Playing",
    console: "Console: PSX",
    type: "PSX",
    year: "Year: 1998",
  },
  {
    id: 5,
    name: "Syphon Filter",
    image: "images/syphonFilterCover.jpg",
    genre: "Genre: Action, Shooter",
    console: "Console: PSX",
    type: "PSX",
    year: "Year: 1999",
  },
];
