export const SNES = [
  {
    id: 0,
    name: "Mickey and Donald - Magical Adventure 3",
    image: "images/mickeyDonaldCover.jpg",
    genre: "Genre: Action-Adventure",
    console: "Console: SNES",
    type: "SNES",
    year: "Year: 1995",
  },
  {
    id: 1,
    name: "Final Fantasy VI ",
    image: "images/finalFantasyVICover.jpg",
    genre: "Genre: Role-Playing",
    console: "Console: SNES",
    type: "SNES",
    year: "Year:  1994",
  },
  {
    id: 3,
    name: "Super Ghols 'n Ghost",
    image: "images/superGhoulsNGhostsCover.jpg",
    genre: "Genre:  Action Side-Scrolling Platform",
    console: "Console: SNES",
    type: "SNES",
    year: "Year: 1991",
  },
  {
    id: 4,
    name: "Super Metroid",
    image: "images/superMetroidCover.jpg",
    genre: "Genre: Action, Adventure",
    console: "Console: SNES",
    type: "SNES",
    year: "Year: 1994",
  },
  {
    id: 5,
    name: "Wild Guns",
    image: "images/WIldGunsCover.jpg",
    genre: "Genre:  Space Western Shooting Gallery",
    console: "Console: SNES",
    type: "SNES",
    year: "Year: 1996 ",
  },
];
