export const TOPFIVE = [
  {
    id: 1,
    name: "Gran Turismo ",
    image: "images/granTurismoCover.jpg",
    genre: "Genre: Driving/Racing, Simulation",
    console: "Console: PSX",
    type: "PSX",
    year: "Year: 1999",
  },
  {
    id: 11,
    name: "Final Fantasy VI ",
    image: "images/finalFantasyVICover.jpg",
    genre: "Genre: Role-Playing",
    console: "Console: SNES",
    type: "SNES",
    year: "Year:  1994",
  },
  {
    id: 4,
    name: "Parasite Eve",
    image: "images/parasiteEveCover.jpg",
    genre: "Genre: Action, Adventure, Role-Playing",
    console: "Console: PSX",
    type: "PSX",
    year: "Year: 1998",
  },
  {
    id: 0,
    name: "Castlevania Symphony Of The Night",
    image: "images/castlevaniaSOTNCover.jpg",
    genre: "Genre: Action-Adventure",
    console: "Console: PSX",
    type: "PSX",
    year: "Year: 1997",
  },
  {
    id: 14,
    name: "Wild Guns",
    image: "images/WIldGunsCover.jpg",
    genre: "Genre:  Space Western Shooting Gallery",
    console: "Console: SNES",
    type: "SNES",
    year: "Year: 1996 ",
  },
];
