export const TOPFIVE = [
  {
    id: 1,
    name: "Golden Axe II ",
    image: "images/goldenAxeIICover.jpg",
    genre: "Genre: Side-Scrolling Beat 'em Up",
    console: "Console: Mega Drive",
    type: "MegaDrive",
    year: "Year: 1991",
  },
  {
    id: 2,
    name: "Final Fantasy VI ",
    image: "images/finalFantasyVICover.jpg",
    genre: "Genre: Role-Playing",
    console: "Console: SNES",
    type: "SNES",
    year: "Year:  1994",
  },
  {
    id: 3,
    name: "Parasite Eve",
    image: "images/parasiteEveCover.jpg",
    genre: "Genre: Action, Adventure, Role-Playing",
    console: "Console: PSX",
    type: "PSX",
    year: "Year: 1998",
  },
  {
    id: 4,
    name: "Castlevania Symphony Of The Night",
    image: "images/castlevaniaSOTNCover.jpg",
    genre: "Genre: Action-Adventure",
    console: "Console: PSX",
    type: "PSX",
    year: "Year: 1997",
  },
  {
    id: 5,
    name: "Wild Guns",
    image: "images/WIldGunsCover.jpg",
    genre: "Genre:  Space Western Shooting Gallery",
    console: "Console: SNES",
    type: "SNES",
    year: "Year: 1996 ",
  },
];
